#!/usr/bin/env python3
"""Generates the media test fixtures in this directory (Pillow >= 11 with WebP, heif-enc).

Run from this directory: python3 generate.py
Large images (6000 x 4000 and the like) are generated by the tests themselves.
"""
import struct
import subprocess
import zlib

from PIL import Image, ImageDraw


def halves(size, left, right, mode="RGB"):
    img = Image.new(mode, size, left)
    ImageDraw.Draw(img).rectangle([size[0] // 2, 0, size[0], size[1]], fill=right)
    return img


def exif_with_gps_camera_date(orientation=1):
    exif = Image.Exif()
    exif[0x010F] = "PresserlCam"          # Make
    exif[0x0110] = "Spy 3000"             # Model
    exif[0x0132] = "2026:09:27 10:15:00"  # DateTime
    exif[0x0112] = orientation
    exif.get_ifd(0x8769)[0x9003] = "2026:09:27 10:15:00"  # DateTimeOriginal
    gps = exif.get_ifd(0x8825)
    gps[1] = "N"
    gps[2] = (48.0, 18.0, 30.0)
    gps[3] = "E"
    gps[4] = (14.0, 17.0, 10.0)
    return exif


XMP = (b'<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
       b'<rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/" dc:creator="Secret Photographer"/>'
       b'</rdf:RDF></x:xmpmeta>')

# JPEG from a phone: EXIF with GPS, camera and date, XMP and a comment
halves((640, 480), (200, 40, 40), (40, 40, 200)).save(
    "photo-gps.jpg", quality=90, exif=exif_with_gps_camera_date(), xmp=XMP, comment=b"taken at home")

# 400 x 300, red left half, blue right half, EXIF orientation 6 (rotate 90 degrees clockwise)
halves((400, 300), (255, 0, 0), (0, 0, 255)).save(
    "rotated-6.jpg", quality=95, exif=exif_with_gps_camera_date(orientation=6))

# PNG without transparency, 1200 x 800
halves((1200, 800), (30, 160, 30), (230, 230, 30)).save("opaque.png")

# PNG with an alpha channel that is fully opaque
halves((300, 200), (30, 160, 30, 255), (230, 230, 30, 255), "RGBA").save("opaque-alpha.png")

# PNG with transparency
halves((300, 200), (30, 160, 30, 255), (0, 0, 0, 0), "RGBA").save("transparent.png")

# WebP lossy without alpha, WebP lossless with transparency, animated WebP
halves((320, 240), (10, 120, 200), (250, 140, 0)).save("photo.webp", quality=80)
halves((200, 100), (200, 20, 20, 255), (0, 0, 0, 0), "RGBA").save("transparent.webp", lossless=True)
frames = [Image.new("RGB", (64, 64), c) for c in [(255, 0, 0), (0, 255, 0)]]
frames[0].save("animated.webp", save_all=True, append_images=frames[1:], duration=100, loop=0)

# GIF and HEIC: refused types
Image.new("RGB", (32, 32), (0, 0, 255)).save("image.gif")
Image.new("RGB", (64, 64), (0, 128, 0)).save("heic-source.png")
subprocess.run(["heif-enc", "-q", "50", "-o", "image.heic", "heic-source.png"], check=True,
               stdout=subprocess.DEVNULL)
subprocess.run(["rm", "heic-source.png"], check=True)

# HTML disguised as a JPEG
with open("cat.jpg", "wb") as f:
    f.write(b"<!DOCTYPE html><html><body><script>alert('hi')</script></body></html>\n")


# Decompression bomb: a PNG that declares 30000 x 30000 RGB pixels but carries only the first rows
def chunk(kind, data):
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)


width = height = 30000
rows = zlib.compressobj(9)
data = b""
row = b"\x00" + bytes(width * 3)
for _ in range(60):
    data += rows.compress(row)
data += rows.flush(zlib.Z_SYNC_FLUSH)
with open("bomb.png", "wb") as f:
    f.write(b"\x89PNG\r\n\x1a\n")
    f.write(chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)))
    f.write(chunk(b"IDAT", data))
    f.write(chunk(b"IEND", b""))
